# Generated by Django 5.0.6 on 2024-07-09 08:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagerapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('To Do', 'Todo'), ('In Progress', 'Inprogress'), ('In Review', 'Inreview'), ('Done', 'Done')], default='To Do', max_length=20)),
                ('startDate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('deadline', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Very High', 'Veryhigh')], default='High', max_length=20)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
